---
title: "Optimisation on Brown-Resnick max-stable processes"
author: " "
date: "`r Sys.Date()`" 
output:
  pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 5, fig.height = 5,
                      fig.align = 'center', message = FALSE, warning = FALSE,
                      fig.pos='H', echo=FALSE)

```


```{r lib, echo=FALSE}
# setwd("./script")
library(generain)
library(reshape2)
library(ggplot2)
source("load_libraries.R")
library(kableExtra)
library(extRemes)
library(bbmle)
library(ismev)
library(extRemes)
library(evd)
library(dplyr)
library(latex2exp)

btf_theme <- theme_minimal() +
  theme(axis.text.x = element_text(size =  6, angle = 0),
        axis.text.y = element_text(size = 6),
        axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        legend.title = element_text(size = 8),
        legend.text = element_text(size = 6),
        title = element_text(size = 10),
        axis.line = element_blank(),  # Remove axis lines
        panel.border = element_blank(),  # Remove plot border
        panel.background = element_rect(fill = "transparent", color = NA),
        # Remove plot background
        axis.text = element_blank(),  # Remove axis text
        axis.ticks = element_blank(),  # Remove axis ticks
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.grid = element_line(color = "#5c595943"))

# my green color
btfgreen <- "#69b3a2"
```

# Simulations of max-stable processes with Brown-Resnick dependence

## Without advection

```{r sim25s300t, fig.width = 5, fig.height = 5}
adv <- c(0, 0)
params <- c(0.4, 0.2, 1.5, 1) # ok verif sur simu
true_param <- c(params, adv)
ngrid <- 5
spa <- 1:ngrid
nsites <- ngrid^2 # if the grid is squared
temp <- 1:300

# get folder name
if (any(adv < 1)) {
  adv_int <- adv * 10
} else {
  adv_int <- adv
}
adv_str <- sprintf("%02d_%02d", adv_int[1], adv_int[2])

# Save the data
foldername <- paste0("../data/simulations_BR/sim_", ngrid^2, "s_",
                                length(temp), "t_", adv_str, "/")


if (!dir.exists(foldername)) {
  dir.create(foldername, recursive = TRUE)
}


nres <- 10
BR <- sim_BR(true_param[1], true_param[2], true_param[3],
            true_param[4], spa, spa, temp, adv = adv, nres = nres)

save_simulations(BR, ngrid, nres, folder = foldername,
        file = paste0("br_", ngrid^2, "s_", length(temp), "t"), forcedind = 1)

# get number of files in the folder
nfiles <- length(list.files(foldername))

# load simulated data in a list
simu_list <- list()

for (i in 1:nfiles) {
    file_path <- paste0(foldername, "br_", ngrid^2, "s_", length(temp), "t_", i,
                        ".csv")
    simu_temp <- read.csv(file_path)
    simu_list[[i]] <- simu_temp
}

simu_df <- simu_list[[1]]
nsites <- ncol(simu_df)
sites_coords <- generate_grid_coords(sqrt(nsites))
```

```{r, echo=FALSE}
# plot the simulations
par(mfrow = c(2, 2), cex = 0.5, main = "Simulated data")
plot(simu_df[, 1], main = "Site 1")
plot(simu_df[, 2], main = "Site 2")
plot(simu_df[, 3], main = "Site 3")
plot(simu_df[, 4], main = "Site 4")
```

# Compute joint exceedances

```{r}

```


```{r plotdenskijnewsim2, fig.height=7, fig.width=7, echo=FALSE, eval=FALSE}
df_lags <- get_lag_vectors(sites_coords, true_param, tau_max = 10)
q <- 0.92
excesses <- empirical_excesses(simu_df, q, df_lags, type = "brownresnick")

excesses <- excesses[excesses$kij > 0, ]
n_marg <- get_marginal_excess(simu_df, quantile = q)
# Tobs <- excesses$Tobs # T - tau
Tmax <- nrow(simu_df)
p_hat <- n_marg / Tmax # probability of marginal excesses
kij <- excesses$kij # number of joint excesses
excesses$hnorm <- sqrt(excesses$hx^2 + excesses$hy^2)
chi_theorical <- theorical_chi(true_param, df_lags)

tau_values <- unique(excesses$tau)

plot_data <- data.frame()

for (tau in tau_values) {
  hnorm <- 1 # fixed hnorm
  chi_tau_h <- chi_theorical$chi[chi_theorical$tau == tau &
                                 chi_theorical$hnorm == hnorm]
  k_tau_h <- excesses$kij[excesses$tau == tau &
                          excesses$hnorm == hnorm]

  proba_tau_h <- unique(chi_tau_h * p_hat)
  Tobs <- Tmax - tau # t - tau

  # Empirical density
  density_data <- density(k_tau_h)
  density_df <- data.frame(x = density_data$x,
          y = density_data$y, tau = as.factor(tau), type = "Empirical")

  # Theorical binomial distribution
  x_vals <- 0:Tobs
  binom_y <- dbinom(x_vals, size = Tobs, prob = proba_tau_h)
  binom_df <- data.frame(x = x_vals, y = binom_y,
                         tau = as.factor(tau), type = "Binomial")

  # Combine
  plot_data <- rbind(plot_data, density_df, binom_df)
}

ggplot(plot_data, aes(x = x, y = y, color = type, linetype = type)) +
  geom_line(size = 1) +
  facet_wrap(~tau, scales = "free_y") +
  labs(title = paste0("Density vs Binomial distribution for q = ", q,
              " and hnorm = ", hnorm, " for each tau"),
       x = "Number of excesses",
       y = "Density") +
  theme_minimal() +
  xlim(0, 30) +
  theme(legend.title = element_blank())
```

# Optimisation

```{r, fig.width = 5, fig.height = 5, echo=FALSE}
df_lags <- get_lag_vectors(sites_coords, tau_max = 10)
q <- 0.92
excesses <- empirical_excesses(simu_df, q, df_lags, type = "brownresnick")

result <- optim(par = c(0.4, 0.2, 1.5, 1, 0.001, 0.001), fn = neg_ll,
                  data = simu_df,
                  quantile = q,
                  df_lags = df_lags,
                  excesses = excesses,
                  hmax = sqrt(17),
                  threshold = FALSE,
                  method = "L-BFGS-B",
                  lower = c(1e-6, 1e-6, 1e-6, 1e-6, -Inf, -Inf),
                  upper = c(Inf, Inf, 1.999, 1.999, Inf, Inf),
                  control = list(maxit = 10000))

result$par
# df_result <- data.frame(beta1 =  result$par[1],
#                         beta2 = result$par[2],
#                         alpha1 = result$par[3],
#                         alpha2 = result$par[4],
#                         adv1 = result$par[5],
#                         adv2 = result$par[6])

# df_rmse <- data.frame(beta1 = sqrt((result$par[1] - true_param[1])^2),
#                 beta2 = sqrt((result$par[2] - true_param[2])^2),
#                 alpha1 = sqrt((result$par[3] - true_param[3])^2),
#                 alpha2 = sqrt((result$par[4] - true_param[4])^2),
#                 adv1 = sqrt((result$par[5] - true_param[5])^2),
#                 adv2 = sqrt((result$par[6] - true_param[6])^2))

# df_result <- rbind(df_result, df_rmse)
# rownames(df_result) <- c("estim", "rmse")
# kable(df_result, "latex", booktabs = TRUE,
#         caption = "RMSE for all simulations together")  %>%
#     kable_styling(latex_options = "H",
#         bootstrap_options = c("striped", "hover", "condensed", "responsive"))


# save the result
foldername <- "../data/optim/rpar_noadv/"
if (!dir.exists(foldername)) {
  dir.create(foldername, recursive = TRUE)
}

name_file <- paste0("result_optim_", nres, "simu_", ngrid^2, 
                                "s_", length(temp), "t_" , adv_str, ".csv")

# write.csv(df_result, paste0(foldername, name_file))
# get csv
df_result <- read.csv(paste0(foldername, name_file))
colnames(df_result) <- c("", "beta1", "beta2", "alpha1", "alpha2", "adv1", "adv2")
kable(df_result, "latex", booktabs = TRUE,
        caption = "Result and RMSE for all replicates together with advection=(0,0)")  %>%
    kable_styling(latex_options = "H",
        bootstrap_options = c("striped", "hover", "condensed", "responsive"))

```


# With advection

```{r sim25s300t, fig.width = 5, fig.height = 5}
adv <- c(0.1, 0.5)
params <- c(0.4, 0.2, 1.5, 1) # ok verif sur simu
true_param <- c(params, adv)
ngrid <- 5
spa <- 1:ngrid
nsites <- ngrid^2 # if the grid is squared
temp <- 1:300

# get folder name
if (all(adv == c(0, 0))) {
    foldername <- paste0("../data/simulations_BR/sim_", ngrid^2, "s_",
                                length(temp), "t/")
} else {
    adv_int <- adv * 10
    adv_str <- sprintf("%02d%02d", adv_int[1], adv_int[2])

    # Save the data
    foldername <- paste0("../data/simulations_BR/sim_", ngrid^2, "s_",
                                    length(temp), "t_adv_", adv_str, "/")

}

# BR <- sim_BR(true_param[1], true_param[2], true_param[3],
#             true_param[4], spa, spa, temp, adv = adv, nres = 10)

# save_simulations(BR, ngrid, n.BR, folder = foldername,
#         file = paste0("br_", ngrid^2, "s_", length(temp), "t"), forcedind = 1)

# get number of files in the folder
nfiles <- length(list.files(foldername))

# load simulated data in a list
simu_list <- list()

for (i in 1:nfiles) {
    file_path <- paste0(foldername, "br_", ngrid^2, "s_", length(temp), "t_", i,
                        ".csv")
    simu_temp <- read.csv(file_path)
    simu_list[[i]] <- simu_temp
}

simu_df <- simu_list[[1]]
nsites <- ncol(simu_df)
sites_coords <- generate_grid_coords(sqrt(nsites))
```

```{r, echo=FALSE}
# plot the simulations
par(mfrow = c(2, 2), cex = 0.5, main = "Simulated data")
plot(simu_df[, 1], main = "Site 1")
plot(simu_df[, 2], main = "Site 2")
plot(simu_df[, 3], main = "Site 3")
plot(simu_df[, 4], main = "Site 4")
```

# Optimisation

```{r, fig.width = 5, fig.height = 5, echo=FALSE}
df_lags <- get_lag_vectors(sites_coords, true_param,
                                        tau_max = 10)
q <- 0.95
excesses <- empirical_excesses(simu_df, q, df_lags, type = "br")

result <- optim(par = true_param, fn = neg_ll,
                  data = simu_df,
                  quantile = q,
                  df_lags = df_lags,
                  excesses = excesses,
                  hmax = NA,
                  threshold = FALSE,
                  method = "L-BFGS-B",
                  lower = c(1e-6, 1e-6, 1e-6, 1e-6, -Inf, -Inf),
                  upper = c(Inf, Inf, 1.999, 1.999, Inf, Inf),
                  control = list(parscale = c(1, 1, 1, 1, 1, 1),
                                 maxit = 10000,
                                 ndeps = c(1e-3, 1e-3, 1e-3, 1e-3, 1e-3, 1e-3)))


# df_result <- data.frame(beta1 =  result$par[1],
#                         beta2 = result$par[2],
#                         alpha1 = result$par[3],
#                         alpha2 = result$par[4],
#                         adv1 = result$par[5],
#                         adv2 = result$par[6])

# df_rmse <- data.frame(beta1 = sqrt((result$par[1] - true_param[1])^2),
#                 beta2 = sqrt((result$par[2] - true_param[2])^2),
#                 alpha1 = sqrt((result$par[3] - true_param[3])^2),
#                 alpha2 = sqrt((result$par[4] - true_param[4])^2),
#                 adv1 = sqrt((result$par[5] - true_param[5])^2),
#                 adv2 = sqrt((result$par[6] - true_param[6])^2))

# df_result <- rbind(df_result, df_rmse)
# rownames(df_result) <- c("estim", "rmse")
# kable(df_result, "latex", booktabs = TRUE,
#         caption = "RMSE for all simulations together")  %>%
#     kable_styling(latex_options = "H",
#         bootstrap_options = c("striped", "hover", "condensed", "responsive"))


# save the result
foldername <- "../data/optim/rpar_noadv/"
if (!dir.exists(foldername)) {
  dir.create(foldername, recursive = TRUE)
}

name_file <- paste0("result_optim_", nres, "simu_", ngrid^2, 
                                "s_", length(temp), "t_" , adv_str, ".csv")

# write.csv(df_result, paste0(foldername, name_file))
# get csv
df_result <- read.csv(paste0(foldername, name_file))
colnames(df_result) <- c("", "beta1", "beta2", "alpha1", "alpha2", "adv1", "adv2")
kable(df_result, "latex", booktabs = TRUE,
        caption = "Result and RMSE for all replicates together with advection=(0,0)")  %>%
    kable_styling(latex_options = "H",
        bootstrap_options = c("striped", "hover", "condensed", "responsive"))

```
