---
title: "Optimisation"
author: " "
date: "`r Sys.Date()`" 
output:
  pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 5, fig.height = 5,
                      fig.align = 'center', message = FALSE, warning = FALSE,
                      fig.pos='H', echo=FALSE)

```


```{r lib, echo=FALSE}
# setwd("./script")
library(generain)
library(reshape2)
library(ggplot2)
source("load_libraries.R")
library(kableExtra)
library(extRemes)
library(bbmle)
library(ismev)
library(extRemes)
library(evd)
library(dplyr)
library(latex2exp)

btf_theme <- theme_minimal() +
  theme(axis.text.x = element_text(size =  6, angle = 0),
        axis.text.y = element_text(size = 6),
        axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        legend.title = element_text(size = 8),
        legend.text = element_text(size = 6),
        title = element_text(size = 10),
        axis.line = element_blank(),  # Remove axis lines
        panel.border = element_blank(),  # Remove plot border
        panel.background = element_rect(fill = "transparent", color = NA),
        # Remove plot background
        axis.text = element_blank(),  # Remove axis text
        axis.ticks = element_blank(),  # Remove axis ticks
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.grid = element_line(color = "#5c595943"))

# my green color
btfgreen <- "#69b3a2"
```


# The $r$-Pareto process without advection and new params

## Simulation

We simulate the $r$-Pareto process with the parameters $\beta_1 = 0.5$,
$\beta_2 = 0.1$, $\alpha_1 = 1.2$, $\alpha_2 = 0.9$ and the advection vector
$V = (0.5, 0.3)$. We simulate the process on a $5 \times 5$ grid with
$30$ time steps and $100$ realizations. We use a conditonal point $s_0 = (1, 1)$ at
time $t_0 = 1$.

```{r rparetosim1, fig.width = 5, fig.height = 5, echo=FALSE, fig.cap="Time series for 4 sites of the first realization in the advection direction"}
adv <- c(0, 0) # advection
params <- c(0.4, 0.2, 1.5, 1.9)
true_param <- c(params, adv)
beta1 <- params[1]
beta2 <- params[2]
alpha1 <- params[3]
alpha2 <- params[4]
ngrid <- 5
spa <- 1:ngrid
nsites <- ngrid^2 # if the grid is squared
temp <- 1:30 # time steps

# Conditional point
s0 <- c(1, 1)
t0 <- 1

# Number of realizations
M <- 1
m <- 10
nres <- M * m

# Simulate the process
set.seed(1234)
simu <- sim_rpareto(beta1, beta2, alpha1, alpha2, spa, spa, temp, adv, s0,
                    t0, nres)

if (any(adv < 1 && adv > 0.1)) {
  adv_int <- adv * 10
  adv_str <- sprintf("%02d_%02d", adv_int[1], adv_int[2])
} else if (adv < 0.1 && adv > 0) {
  adv_int <- adv * 100
  adv_str <- sprintf("%03d_%03d", adv_int[1], adv_int[2])
} else {
  adv_int <- adv
  adv_str <- sprintf("%02d_%02d", adv_int[1], adv_int[2])
}

param_str <- sprintf("%02d_%02d_%02d_%02d", true_param[1] * 10,
                    true_param[2] * 10, true_param[3] * 10, true_param[4] * 10)

# Save the data
foldername <- paste0("../data/simulations_rpar_", param_str,"/sim_", ngrid^2, 
                    "s_", length(temp), "t_", adv_str, "/")


if (!dir.exists(foldername)) {
  dir.create(foldername, recursive = TRUE)
}

save_simulations(simu, ngrid, nres, folder = foldername,
        file = paste0("rpar_", ngrid^2, "s_", length(temp), "t"))
```


```{r rparetosim2, fig.width = 5, fig.height = 5, echo=FALSE, fig.cap="Time series for 4 sites of the first realization in the advection direction"}
ngrid <- 5
spa <- 1:ngrid
nsites <- ngrid^2 # if the grid is squared
temp <- 1:30 # time steps

# Conditional point
s0 <- c(1, 1)
t0 <- 1

get_list_simu <- function(ngrid, temp, adv, m, true_param) {
  if (any(adv < 1 && adv > 0.1)) {
    adv_int <- adv * 10
    adv_str <- sprintf("%02d_%02d", adv_int[1], adv_int[2])
  } else if (adv < 0.1 && adv > 0) {
    adv_int <- adv * 100
    adv_str <- sprintf("%03d_%03d", adv_int[1], adv_int[2])
  } else {
    adv_int <- adv
    adv_str <- sprintf("%02d_%02d", adv_int[1], adv_int[2])
  }

  param_str <- sprintf("%02d_%02d_%02d_%02d", true_param[1] * 10,
               true_param[2] * 10, true_param[3] * 10, true_param[4] * 10)

  # Save the data
  foldername <- paste0("../data/simulations_rpar_", param_str,"/sim_", ngrid^2,
                      "s_", length(temp), "t_", adv_str, "/")

  list_simu <- list() # first simulation of m replicates
  for (i in 1:m) {
    file_name <- paste0(foldername, "rpar_", ngrid^2, "s_",
                          length(temp), "t_", i, ".csv")
    list_simu[[i]] <- read.csv(file_name)
  }
  return(list_simu)
}

```

# Variation of beta1

```{r}
# Initialisation des paramètres
adv <- c(0, 0) # advection
beta_values <- c(0.2, 0.4, 0.8, 1) # les valeurs de beta1 à tester
simulations <- list()

# Création des simulations pour chaque valeur de beta1
for (beta1 in beta_values) {
    params <- c(beta1, 0.2, 1.5, 1)
    true_param <- c(params, adv)
    simulations[[paste0("beta1_", beta1)]] <- get_list_simu(ngrid, temp, adv, m, true_param)
}

# Visualisation des distributions pour chaque site et chaque beta1
par(mfrow = c(5, length(beta_values)))
for (i in 1:5) {
    for (j in 1:length(beta_values)) {
        simu_df <- simulations[[paste0("beta1_", beta_values[j])]][[4]]
        site_data <- simu_df[[paste0("S", i)]]
        plot(site_data, main = paste0("Site ", i, ", beta1 = ", beta_values[j]), xlab = "Value")
    }
}
```

# Variation of beta2

```{r}
# Initialisation des paramètres
adv <- c(0, 0) # advection
beta_values <- c(0.2, 0.4, 0.8, 1) # les valeurs de beta1 à tester
simulations <- list()

# Création des simulations pour chaque valeur de beta1
for (beta2 in beta_values) {
    params <- c(0.4, beta2, 1.5, 1)
    true_param <- c(params, adv)
    simulations[[paste0("beta2_", beta2)]] <- get_list_simu(ngrid, temp, adv, m, true_param)
}

# Visualisation des distributions pour chaque site et chaque beta1
par(mfrow = c(5, length(beta_values)))
for (i in 1:5) {
    for (j in 1:length(beta_values)) {
        simu_df <- simulations[[paste0("beta2_", beta_values[j])]][[5]]
        site_data <- simu_df[[paste0("S", i)]]
        plot(site_data, main = paste0("Site ", i, ", beta2 = ", beta_values[j]), xlab = "Value")
    }
}
```

# Variation of alpha1

```{r}
# Initialisation des paramètres
adv <- c(0, 0) # advection
alpha_values <- c(0.5, 1, 1.5, 1.9) # les valeurs de alpha1 à tester
simulations <- list()

for (alpha1 in alpha_values) {
    params <- c(0.4, 0.2, alpha1, 1)
    true_param <- c(params, adv)
    simulations[[paste0("alpha1_", alpha1)]] <- get_list_simu(ngrid, temp, adv, m, true_param)
}

par(mfrow = c(5, length(alpha_values)))
for (i in 1:5) {
    for (j in 1:length(alpha_values)) {
        simu_df <- simulations[[paste0("alpha1_", alpha_values[j])]][[5]]
        site_data <- simu_df[[paste0("S", i)]]
        plot(site_data, main = paste0("Site ", i, ", alpha1 = ", alpha_values[j]), xlab = "Value")
    }
}
```

# Variation of alpha2

```{r}
# Initialisation des paramètres
adv <- c(0, 0) # advection
alpha_values <- c(0.5, 1, 1.5, 1.9) # les valeurs de alpha1 à tester
simulations <- list()

for (alpha2 in alpha_values) {
    params <- c(0.4, 0.2, 1.5, alpha2)
    true_param <- c(params, adv)
    simulations[[paste0("alpha2_", alpha2)]] <- get_list_simu(ngrid, temp, adv, m, true_param)
}

par(mfrow = c(5, length(alpha_values)))
for (i in 1:5) {
    for (j in 1:length(alpha_values)) {
        simu_df <- simulations[[paste0("alpha2_", alpha_values[j])]][[5]]
        site_data <- simu_df[[paste0("S", i)]]
        plot(site_data, main = paste0("Site ", i, ", alpha2 = ", alpha_values[j]), xlab = "Value")
    }
}
```