---
title: "Simulations of r-Pareto with separated in space and time Gaussian fields"
author: " "
date: "`r Sys.Date()`" 
output:
  pdf_document:
    extra_dependencies: ["float"]
    encoding: "UTF-8"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 7, fig.height = 7,
                      fig.align = 'center', message = FALSE, warning = FALSE,
                      fig.pos='H')
par(cex.main = 1,
    cex.lab = 1,
    cex.axis = 1)
```


```{r lib, echo=FALSE}
# setwd("./script")
library(generain)
library(reshape2)
library(ggplot2)
source("load_libraries.R")
library(kableExtra)
library(extRemes)
library(bbmle)
library(ismev)
library(extRemes)
library(evd)
library(latex2exp)
library(geosphere)
library(RandomFields)

btf_theme <- theme_minimal() +
  theme(axis.text.x = element_text(size =  6, angle = 0),
        axis.text.y = element_text(size = 6),
        axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        legend.title = element_text(size = 8),
        legend.text = element_text(size = 6),
        title = element_text(size = 10),
        axis.line = element_blank(),  # Remove axis lines
        panel.border = element_blank(),  # Remove plot border
        panel.background = element_rect(fill = "transparent", color = NA),
        # Remove plot background
        axis.text = element_blank(),  # Remove axis text
        axis.ticks = element_blank(),  # Remove axis ticks
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.grid = element_line(color = "#5c595943"))

# my green color
btfgreen <- "#69b3a2"
```


# Variogram

## Spatial and temporal grid

```{r}
x <- 1:2
y <- 1:2
t <- 0:4
adv <- c(0, 1)

sx <- seq_along(x)
sy <- seq_along(y)
st <- seq_along(t)

lx <- length(x)
ly <- length(y)
lt <- length(t)

grid_with_advection <- expand.grid(
    x = seq_len(lx),
    y = seq_len(ly),
    t = t
  )
grid_with_advection$shifted_x <- grid_with_advection$x + grid_with_advection$t * adv[1]
grid_with_advection$shifted_y <- grid_with_advection$y + grid_with_advection$t * adv[2]

grid <- grid_with_advection

```


## Gaussian field

```{r}
RandomFields::RFoptions(spConform = FALSE, allow_duplicated_locations = T)

# compute_W_s_t <- function(grid, W_s, W_t, adv) {
#   lx <- length(unique(grid$x))
#   ly <- length(unique(grid$y))
#   lt <- length(unique(grid$t))
#   coords <- cbind(grid$shifted_x, grid$shifted_y)
#   if (all(adv == 0)) {
#     duplicates <- duplicated(coords)
#     filtered_coords <- coords[!duplicates, ]
#     coords <- filtered_coords
#   }
#   nsites <- nrow(coords)
#   W_s_t <- array(NA, dim = c(lx, ly, lt))
#   t_index <- grid$t + 1 # index starts at 1
#   for (i in seq_len(nrow(grid))) {
#       s_x <- grid$x[i]
#       s_y <- grid$y[i]
#       s <- c(s_x, s_y)
#       if (all(adv == 0) & i > nsites) {
#         if (i %% nsites == 0) {
#           ind_W_s <- i - nsites * (i %/% nsites - 1)
#         } else {
#           ind_W_s <- i - nsites * (i %/% nsites)
#         }
#       } else {
#         ind_W_s <- i
#       }
#       W_s_t[s[2], s[1], t_index[i]] <- W_s[ind_W_s] + W_t[t_index[i]]
#   }
#   return(W_s_t)
# }
options(vsc.workspace = FALSE)
options(str = list())
alpha1 <- 1.5
beta1 <- 0.4
modelSpace <- RandomFields::RMfbm(alpha = alpha1, var = beta1) # semivario
modelSpace <- RandomFields::RMfbm(alpha = alpha1, var = 2*beta1) # vario

alpha2 <- 1
beta2 <- 0.2
modelTime <- RandomFields::RMfbm(alpha = alpha2, var = 2*beta2)

x_shifted <- grid$shifted_x
y_shifted <- grid$shifted_y

# create regular advected grid
regular_x <- seq(min(x_shifted), max(x_shifted), by = adv[1])
regular_y <- seq(min(y_shifted), max(y_shifted), by = adv[2])

coords <- cbind(x_shifted, y_shifted)
dist_matrix <- as.matrix(dist(coords))

# W_s <- RandomFields::RFsimulate(
#   model = modelSpace,
#   x = seq_along(unique(x_shifted)),
#   y = seq_along(unique(y_shifted)),
#   grid = T
# )

if (all(adv == 0)) {
  duplicates <- duplicated(coords)
  filtered_coords <- coords[!duplicates, ]
  coords <- filtered_coords
}

W_s <- RandomFields::RFsimulate(
  model = modelSpace,
  x = coords[,1],
  y = coords[,2],
  grid = FALSE
)

# plot(modelSpace)
# curve(2*beta1*x^alpha1, 0, 10, add = TRUE, col = "red")

# plot(modelTime)
# curve(2*beta2*x^alpha2, 0, 10, add = TRUE, col = "red")


W_t <- RandomFields::RFsimulate(modelTime, x = t, n = 1, grid = T)
W <- compute_W_s_t(grid, W_s, W_t, adv)

W[,,1]

W_s[1:4] + W_t[1]

# Histogrammes pour visualiser la distribution
hist(W_s, main = "Histogramme de W_s", xlab = "Valeurs de W_s", breaks = 20)
hist(W_t, main = "Histogramme de W_t", xlab = "Valeurs de W_t", breaks = 20)
```


```{r}
library(ggplot2)
library(reshape2)

# Exemple pour tracer une tranche
k <- 1  # Choisir une tranche
slice <- W[,,k]

# Convertir en format long pour ggplot
slice_df <- melt(slice)
colnames(slice_df) <- c("x", "y", "value")

# Tracer
ggplot(slice_df, aes(x = x, y = y, fill = value)) +
  geom_tile() +
  scale_fill_viridis_c() +
  theme_minimal() +
  ggtitle(paste("Slice", k, "de W"))

```


```{r}
library(geoR)


theoretical_variogram <- function(h, t, beta1, beta2, alpha1, alpha2) {
  vario <- beta1 * h^alpha1 + beta2 * t^alpha2
  return(2*vario)
}


values <- as.vector(W_s)
data_coords <- data.frame(coords, values)
# remove duplicates
duplicates <- dup.coords(data_coords[, 1:2])
data_coords_unique <- data_coords[!duplicates, ]

data_t <- t(data_coords)

duplicates <- duplicated(data_coords[, 1:2])

filtered_data <- data_coords[!duplicates, ]

geo_data <- as.geodata(filtered_data, coords.col = 1:2, data.col = 3)
variog_empirical <- variog(geo_data)
plot(variog_empirical, main = paste("Empirical spatial variogram"))
lines(variog_empirical$u, theoretical_variogram(variog_empirical$u, 0,
                                                0.5*beta1, 0, alpha1, 0),
      col = "red", lwd = 2)

# verif time
# coords <- unique(grid$t)
# values <- as.vector(W_t)


time <- 10
k <- time + 1
slice <- W[,,k]
coords_t <- cbind(grid$shifted_x[grid$t == time], grid$shifted_y[grid$t == time])
values <- as.vector(slice)

data_coords <- data.frame(coords_t, values)
geo_data <- as.geodata(data_coords, coords.col = 1:2, data.col = 3)

variog_empirical <- variog(geo_data)
plot(variog_empirical, main = paste("Empirical variogram for time ", time))
lines(variog_empirical$u, theoretical_variogram(variog_empirical$u, time,
                                                0.5*beta1, 0.5*beta2, alpha1, alpha2),
      col = "red", lwd = 2)

```


```{r}
# compute_gamma_point <- function(grid, gamma_space, gamma_time, adv, s=NA, t=NA) {
#   # Get length of unique values
#   lx <- length(unique(grid$x))
#   ly <- length(unique(grid$y))
#   lt <- length(unique(grid$t))

#   # Get spatial variogram for s
#   if(all(!(is.na(s)) & !(is.na(t)))) {
#     index_grid <- which(grid$shifted_x == s[1] & grid$shifted_y == s[2] &
#                           grid$t == t)
#     gamma_s <- gamma_space[[index_grid]]
#     gamma_t <- gamma_temp[[t + 1]]
#   } else {
#     gamma_s <- gamma_space
#     gamma_t <- gamma_temp
#   }

#   coords <- cbind(grid$shifted_x, grid$shifted_y)
#   if (all(adv == 0)) {
#     duplicates <- duplicated(coords)
#     filtered_coords <- coords[!duplicates, ]
#     coords <- filtered_coords
#   }
#   nsites <- nrow(coords)

#   t_index <- grid$t + 1 # index starts at 1

#   # compute gamma space-time
#   gamma <- array(NA, dim = c(lx, ly, lt))
#   for (i in seq_along(t_index)) {
#     if (all(adv == 0) & i > nsites) {
#         if (i %% nsites == 0) { # get index when no advection
#           ind_g_s <- i - nsites * (i %/% nsites - 1)
#         } else {
#           ind_g_s <- i - nsites * (i %/% nsites)
#         }
#     } else {
#       ind_g_s <- i # get index when advection
#     }
#     vario <- gamma_s[ind_g_s] + gamma_t[t_index[i]]
#     gamma[grid$y[i], grid$x[i], t_index[i]] <- vario
#   }

#   return(gamma)
# }

coords <- cbind(x_shifted, y_shifted)
if (all(adv == 0)) {
  duplicates <- duplicated(coords)
  filtered_coords <- coords[!duplicates, ]
  coords <- filtered_coords
}

gamma_space_0 <- RandomFields::RFvariogram( # for (s0,t0)
      modelSpace,
      x = coords[,1] - 1,
      y = coords[,2] - 1,
    )

N <- nrow(grid) # number of points
gamma_space <- lapply(seq_len(N), function(n) 
        RandomFields::RFvariogram(modelSpace,
          x = x_shifted - grid$shifted_x[n],
          y = y_shifted - grid$shifted_y[n])) # for all s,t

gamma_temp_0 <- RandomFields::RFvariogram( # for t0
    modelTime,
    x = t - t[1]
  )

Nt <- length(t) # number of points
gamma_temp <- lapply(seq_len(Nt), function(n) # for all t
        RandomFields::RFvariogram(modelTime,
          x = t - t[n]))

all(gamma_temp[[1]] == gamma_temp_0)
all(gamma_space[[1]] == gamma_space_0)

# plot(gamma_space[[1]], main = "Variogramme spatial /à s0,t0")
# plot(gamma_space_0, main = "Variogramme spatial /à s0,t0")
# plot(gamma_temp[[1]], main = "Variogramme temporel")
# plot(gamma_temp_0, main = "Variogramme temporel")

# verif space
index_coords <- 7
s_x <- coords[index_coords, 1]
s_y <- coords[index_coords, 2]
dist_matrix <- as.matrix(dist(coords))
dist_s0 <- dist_matrix[,1]
h_vect <- sort(unique(as.vector(dist_s0)))
s <- c(s_x, s_y)

# s0 <- grid[1, 1:2]
# index_grid <- 1
# s_x <- grid[index_grid, 4]
# s_y <- grid[index_grid, 5]
dist_matrix <- as.matrix(dist(coords))
dist_s0 <- dist_matrix[,1]
h_vect <- sort(unique(as.vector(dist_s0)))
s <- c(s_x, s_y)
h <- c(s_x - s0[1], s_y - s0[2])
# s_adv <- s + t * adv
gamma_s <- 2 * beta1 * sqrt(h$x^2 + h$y^2)^alpha1


# verif temp
t0 <- 0
t_i <- grid$t[index_coords]
gamma_t <- 2 * beta2 * abs(t_i)^alpha2
gamma_t == gamma_temp[[t_i + 1]][1]


ind_grid <- which(grid$shifted_x == s_x && grid$shifted_y == s_y &&
                          grid$t == t_i)
gamma_h_t <- gamma_s + gamma_t
gamma <- compute_gamma_point(grid, gamma_space_0, gamma_temp_0, adv)

gamma[,,t_i + 1]

gamma_st_0 <- gamma_space_0[5:8] + gamma_temp_0[2]
gamma[1,2,2]

s_noadv <- s - t_i * adv
# print(gamma_h_t)
# print(gamma[s[1], s[2], t_i + 1])
gamma_h_t == gamma[s_noadv[1], s_noadv[2], t_i + 1]
gamma[,,t_i + 1]
```


# Simulation r-Pareto

```{r}
# Simulate
beta1 <- 0.4
beta2 <- 0.2
alpha1 <- 1.5
alpha2 <- 1.
ngrid <- 5
spa <- 1:ngrid
nsites <- ngrid^2 # if the grid is squared
temp <- 0:30
adv <- c(0.2, 0.1)
true_param <- c(beta1, beta2, alpha1, alpha2, adv)

M <- 10
m <- 1000
nres <- M * m

s0 <- c(1, 1)
t0 <- 0
# Simulate the process
# set.seed(123)
simu <- sim_rpareto(beta1, beta2, alpha1, alpha2, spa, spa, temp, adv, s0,
                    t0, nres)

if (any(adv < 1 && adv >= 0.1)) {
  adv_int <- adv * 10
  adv_str <- sprintf("%02d_%02d", adv_int[1], adv_int[2])
} else if (any(adv < 0.1 && adv > 0)) {
  adv_int <- adv * 100
  adv_str <- sprintf("%03d_%03d", adv_int[1], adv_int[2])
} else {
  adv_int <- adv
  adv_str <- sprintf("%02d_%02d", adv_int[1], adv_int[2])
}

param_str <- sprintf("%02d_%02d_%02d_%02d", true_param[1] * 10,
                    true_param[2] * 10, true_param[3] * 10, true_param[4] * 10)

s0_str <- sprintf("%01d_%01d", s0[1], s0[2])
setwd("./script")
# Save the data
foldername <- paste0("../data/simulations_rpar/rpar_", param_str, "_", adv_str,
                   "/sim_", ngrid^2, "s_", length(temp), "t_s0_",
                    s0_str, "/")


if (!dir.exists(foldername)) {
  dir.create(foldername, recursive = TRUE)
}
save_simulations(simu, ngrid, nres, folder = foldername,
        file = paste0("rpar_", ngrid^2, "s_", length(temp), "t"))

list_simu <- list()
for (i in 1:nres) {
  file_name <- paste0(foldername, "rpar_", ngrid^2, "s_",
                        length(temp), "t_", i, ".csv")
  list_simu[[i]] <- read.csv(file_name)
}

list_simuM <- list()
for (i in 1:nres) {
  file_name <- paste0(foldername, "rpar_", ngrid^2, "s_",
                        length(temp), "t_", i, ".csv")
  list_simuM[[i]] <- read.csv(file_name)
}

# Concatenate all the simulations by m replicates
# list_simu_all <- list()
# for(i in 1:M) {
#   list_simu_all[[i]] <- do.call(rbind, list_simu[((i - 1) * m + 1):(i * m)])
# }

simu_df <- list_simu[[1]]
simu_array <- simu[,,,1]

# simu_df$S1 == simu_array[1,1,]
# simu_array[3,3,2] == simu_df$S13[2]

# Plot the first simulations combining m replicates
simu_all <- list_simuM[[1]]
par(mfrow = c(2, 2),
    cex = 0.7,
    pin = c(2, 1),
    lwd = 0.5,
    col = btfgreen)
plot(simu_all$S1, main = "S1=S0", xlab = "Time", ylab = "Rainfall")
plot(simu_all$S2, main = "S2", xlab = "Time", ylab = "Rainfall")
plot(simu_all$S10, main = "S10", xlab = "Time", ylab = "Rainfall")
plot(simu_all$S25, main = "S20", xlab = "Time", ylab = "Rainfall")
```


```{r}
i = 1
u = 1
mreplicates <- list_simu[((i - 1) * m + 1):(i * m)]

sites_coords <- generate_grid_coords(ngrid)
df_lags <- get_conditional_lag_vectors(sites_coords, s0, t0, tau_vect = 0:10)
th_chi <- theoretical_chi(true_param, df_lags)
par(mfrow=c(1, 1))
plot(th_chi$chi[th_chi$hnormV > 1 & th_chi$hnormV < 2])
# Compute excesses
list_excesses <- lapply(mreplicates, function(replicate) {
  empirical_excesses_rpar(replicate, u, df_lags, threshold = TRUE, t0 = t0)
})

list_excesses[[1]]
# Optimize
result <- optim(
  par = true_param,
  fn = neg_ll_composite_simu,
  list_simu = mreplicates,
  quantile = u,
  df_lags = df_lags,
  list_excesses = list_excesses,
  hmax = sqrt(17),
  s0 = s0,
  t0 = t0,
  threshold = TRUE,
  method = "L-BFGS-B",
  lower = c(1e-8, 1e-8, 1e-8, 1e-8, -Inf, -Inf),
  upper = c(Inf, Inf, 1.999, 1.999, Inf, Inf),
  control = list(maxit = 10000)
)

result$par
```

```{r}
library(parallel)
num_cores <- detectCores() - 1  # Reserve 1 core for the OS

# Parallel execution
sites_coords <- generate_grid_coords(ngrid)
df_lags <- get_conditional_lag_vectors(sites_coords, s0, t0, tau_vect = 0:10)
u <- 1 # threshold corresponding to the r-pareto simulation
result_list <- mclapply(1:M, process_simulation, M = M, m = m,
                        list_simuM = list_simuM, u = 1, df_lags = df_lags,
                        s0 = s0, t0 = t0, true_param = true_param,
                        mc.cores = num_cores)

# Combine results into a data frame
df_result_all <- do.call(rbind, result_list)
colnames(df_result_all) <- c("beta1", "beta2", "alpha1",
                              "alpha2", "adv1", "adv2")

library(latex2exp)

df_bplot <- as.data.frame(df_result_all)

df_bplot <- stack(df_bplot)

ggplot(df_bplot, aes(x = ind, y = values)) +
  geom_boxplot() +
  labs(title = "",
    x = "Parameters", y = "Estimated values") +
  theme_minimal() +
  geom_point(aes(y = true_param[as.numeric(ind)]), color = "red", pch=4) +
  scale_x_discrete(labels = c(TeX("$\\widehat{\\beta}_1$"),
                                TeX("$\\widehat{\\beta}_2$"),
                                TeX("$\\widehat{\\alpha}_1$"),
                                TeX("$\\widehat{\\alpha}_2$"), 
                                TeX("$\\widehat{v}_x$"),
                                TeX("$\\widehat{v}_y$")))

# save the results
foldername <- paste0("../images/optim/euclidean_dist/")
filename <- paste0("boxplot_optim_", M, "simu_", m, "rep_", ngrid^2,
                    "s_", length(temp), "t_", param_str, ".png")

ggsave(paste0(foldername, filename), width = 10,
            height = 10)
```



## Simulation of Brown-Resnick processes

```{r}
sim_BR <- function(beta1, beta2, alpha1, alpha2, x, y, t, adv = NA, nres = 1) {
  ## Setup
  RandomFields::RFoptions(spConform = FALSE, install="no")
  lx <- length(sx <- seq_along(x))
  ly <- length(sy <- seq_along(y))
  lt <- length(st <- seq_along(t))

  ## Model-Variogram BuhlCklu
  modelSpace <- RandomFields::RMfbm(alpha = alpha1, var = 2*beta1)
  modelTime <- RandomFields::RMfbm(alpha = alpha2, var = 2*beta2)

  ## Construct grid
  grid_with_advection <- expand.grid(
    x = seq_len(lx),
    y = seq_len(ly),
    t = t
  )

  grid_with_advection$shifted_x <- grid_with_advection$x +
                                    grid_with_advection$t * adv[1]
  grid_with_advection$shifted_y <- grid_with_advection$y +
                                    grid_with_advection$t * adv[2]

  grid <- grid_with_advection

  coords <- grid[, 4:5]

  if (all(adv == 0)) {
    duplicates <- duplicated(coords)
    filtered_coords <- coords[!duplicates, ]
    coords <- filtered_coords
  }

  ## Variogram
  N <- nrow(grid) # number of points
  gamma_space <- lapply(seq_len(N), function(n) 
          RandomFields::RFvariogram(modelSpace,
            x = grid$shifted_x - grid$shifted_x[n],
            y = grid$shifted_y - grid$shifted_y[n])) # for all s,t

  gamma_temp <- lapply(seq_len(lt), function(n) # for all t
          RandomFields::RFvariogram(modelTime,
            x = t - t[n]))

  ## Main
  Z <- array(, dim = c(lx, ly, lt, nres)) # 4d array
  E <- matrix(rexp(nres * N), nrow = nres, ncol = N)
  for (i in seq_len(nres)) { ## n=1
    V <- 1 / E[i, 1]
 
    # Spatial gaussian random field on shifted coords
    W_s <- RandomFields::RFsimulate(modelSpace, coords[, 1], coords[, 2],
                                      grid = FALSE)
    # Temporal gaussian random field
    W_t <- RandomFields::RFsimulate(modelTime, t, n = 1, grid = TRUE)
    # Spatio-temporal random field
    W <- compute_W_s_t(grid, W_s, W_t, adv)

    gamma_0 <- compute_gamma_point(grid, gamma_space, gamma_temp, adv,
                                 s = c(1, 1), t = 0)
    Y <- exp(W - W[1] - gamma_0)
    Z[, , , i] <- V * Y
    ## n in {2,..,N}
    for (n in 2:N) {
      Exp <- E[i, n]
      V <- 1 / Exp 
      while (V > Z[N * (i - 1) + n]) {
        # Spatial gaussian random field on shifted coords
        W_s <- RandomFields::RFsimulate(modelSpace, coords[, 1], coords[, 2],
                                          grid = FALSE)
        # Temporal gaussian random field
        W_t <- RandomFields::RFsimulate(modelTime, t, n = 1, grid = TRUE)
        # Spatio-temporal random field
        W <- compute_W_s_t(grid, W_s, W_t, adv)
        s <- c(grid$shifted_x[n], grid$shifted_y[n])
        time <- grid$t[n]
        gamma <- compute_gamma_point(grid, gamma_space, gamma_temp, adv, s,
                                     time)
        Y <- exp(W - W[n] - gamma)
        if(all(V * Y[seq_len(n-1)] < Z[(N*(i-1)+1):(N*(i-1)+(n-1))]))
          Z[, , , i] <- pmax(V * Y, Z[, , , i])
          Exp <- Exp + rexp(1)
          V <- 1 / Exp
      }
    }
  }
  ## Return
  Z
}


beta1 <- 0.4
beta2 <- 0.2
alpha1 <- 1.5
alpha2 <- 1
ngrid <- 5
spa <- 1:ngrid
nsites <- ngrid^2 # if the grid is squared
temp <- 0:99
adv <- c(0., 0.)
true_param <- c(beta1, beta2, alpha1, alpha2, adv)

nres <- 2

simu <- sim_BR(beta1, beta2, alpha1, alpha2, spa, spa, temp, adv, nres)


if (any(adv < 1 && adv >= 0.1)) {
  adv_int <- adv * 10
  adv_str <- sprintf("%02d_%02d", adv_int[1], adv_int[2])
} else if (any(adv < 0.1 && adv > 0)) {
  adv_int <- adv * 100
  adv_str <- sprintf("%03d_%03d", adv_int[1], adv_int[2])
} else {
  adv_int <- adv
  adv_str <- sprintf("%02d_%02d", adv_int[1], adv_int[2])
}

param_str <- sprintf("%02d_%02d_%02d_%02d", true_param[1] * 10,
                    true_param[2] * 10, true_param[3] * 10, true_param[4] * 10)

setwd("./script")
# Save the data
foldername <- paste0("../data/simulations_br/br_", param_str, "_", adv_str,
                   "/sim_", ngrid^2, "s_", length(temp), "t", "/")


if (!dir.exists(foldername)) {
  dir.create(foldername, recursive = TRUE)
}
save_simulations(simu, ngrid, nres, folder = foldername,
        file = paste0("br_", ngrid^2, "s_", length(temp), "t"))

list_simu <- list()
for (i in 1:nres) {
  file_name <- paste0(foldername, "br_", ngrid^2, "s_",
                        length(temp), "t_", i, ".csv")
  list_simu[[i]] <- read.csv(file_name)
}

simu_df <- list_simu[[1]]

par(mfrow = c(2, 2),
    cex = 0.7,
    pin = c(2, 1),
    lwd = 0.5,
    col = btfgreen)
plot(simu_df$S1, main = "S1=S0", xlab = "Time", ylab = "Rainfall")
plot(simu_df$S2, main = "S2", xlab = "Time", ylab = "Rainfall")
plot(simu_df$S10, main = "S10", xlab = "Time", ylab = "Rainfall")
plot(simu_df$S25, main = "S20", xlab = "Time", ylab = "Rainfall")
```



```{r}
sites_coords <- generate_grid_coords(ngrid)
df_lags <- get_lag_vectors(sites_coords, tau_max = 10)
th_chi <- theoretical_chi(true_param, df_lags)

q <- 0.99
excesses <- empirical_excesses(simu_df, q, df_lags, type = "brownresnick")

# Optimize
result <- optim(
  par = true_param,
  fn = neg_ll,
  data = simu_df,
  quantile = q,
  df_lags = df_lags,
  excesses = excesses,
  hmax = sqrt(17),
  threshold = FALSE,
  method = "L-BFGS-B",
  lower = c(1e-8, 1e-8, 1e-8, 1e-8, -Inf, -Inf),
  upper = c(Inf, Inf, 1.999, 1.999, Inf, Inf),
  control = list(maxit = 10000)
)

result$par
 ```
