#!/bin/bash
##
#SBATCH --job-name=estim_com1
#SBATCH --ntasks-per-node=27
#SBATCH --ntasks-per-core=1
#SBATCH --mem=50G
#SBATCH --partition=imag
#SBATCH --output=%x_%j.out

export LD_LIBRARY_PATH=$HOME/local/udunits2/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=$HOME/local/udunits2/lib/pkgconfig:$PKG_CONFIG_PATH

WORK_DIR="/home/serrec/work_rainstsimu/rpareto"
CONFIG_FILE=$WORK_DIR/config_com.R

module load R
module load geos
module load gdal

# Récupération des arguments
MIN_DIST=$1
DELTA=$2
Q=$3

cat << EOF > $CONFIG_FILE
min_spatial_dist <- $MIN_DIST
delta <- $DELTA
q <- $Q
distance_type <- "lalpha"
fixed_eta1 <- NA
fixed_eta2 <- NA
EOF

Rscript $WORK_DIR/comephore_muse.R
