# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install remotes
        run: Rscript -e 'install.packages("remotes")'

      - name: Install dependencies for RandomFields
        run: Rscript -e 'install.packages(c("sp", "Rcpp"), repos = "https://cran.r-project.org")'
      
      # - name: Install RandomFields from local archive
      #   run:  Rscript -e 'install.packages("inst/archives/RandomFields_3.3.14.tar.gz", repos = NULL, type = "source")'

      # - name: Install RandomFieldsUtils from local archive
      #   run:  Rscript -e 'install.packages("inst/archives/RandomFieldsUtils_1.2.5.tar.gz", repos = NULL, type = "source")'

      - name: Install RandomFields from MRAN snapshot
        run: Rscript -e 'install.packages("RandomFields", repos = "https://cran.microsoft.com/snapshot/2021-04-01/")'

      - name: Install RandomFieldsUtils from MRAN snapshot
        run: Rscript -e 'install.packages("RandomFieldsUtils", repos = "https://cran.microsoft.com/snapshot/2021-04-01/")'

      - name: Install sessioninfo and rcmdcheck
        run: Rscript -e 'install.packages(c("sessioninfo", "rcmdcheck"))'
      
      # - name: Install pak
      #   run: Rscript -e 'install.packages("pak", repos = "https://r-lib.github.io/p/pak/stable")'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
