name: R-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Change to macOS or windows-latest if needed
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.1"  # Adjust to match your R setup

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev
          sudo apt-get install -y libfontconfig1-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev  # Fix for ragg issues
          sudo apt-get install -y libgit2-dev

      - name: Install dependencies from inst/archives
        run: |
          Rscript -e "
          required_pkgs <- list(
            'kableExtra' = '1.3.4',
            'systemfonts' = '1.0.2',
            'geosphere' = '1.5-10',
            'sp' = '1.4-5',
            'RandomFieldsUtils' = '1.2.5',
            'RandomFields' = '3.3.14'
          )
        
          for (pkg in names(required_pkgs)) {
            required_version <- required_pkgs[[pkg]]
            
            if (!requireNamespace(pkg, quietly = TRUE)) {
              
              archive_path <- file.path('./inst/archives', paste0(pkg, '_', required_version, '.tar.gz'))
              
              if (file.exists(archive_path)) {
                message(paste('Installing', pkg, 'from local archive...'))
                install.packages(archive_path, repos = NULL, type = 'source')
                } else {
                message(paste('Installing', pkg, 'from CRAN...'))
                tryCatch({
                  install.packages(pkg)
                }, error = function(e) {
                  message(paste('Failed to install', pkg, ':', e$message))
                })
              }
            } 
          }
          "

      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            remotes
            devtools
            geosphere
            sp
          needs: dependencies

      - name: Install package from source
        run: R CMD INSTALL .

      - name: Check package
        run: R CMD check --no-manual --as-cran .
