name: R-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner for faster builds
    strategy:
      matrix:
        r-version: ['4.1.1']  # Test on multiple R versions

    steps:
      # Step 1: Check out the code from the repository
      - uses: actions/checkout@v4

      # Step 2: Set up the specified version of R
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      # Step 3: Install required R packages including rcmdcheck
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "testthat", "rcmdcheck"))  # Ensure rcmdcheck is installed
          remotes::install_deps(dependencies = TRUE)   # Install the package dependencies
        shell: Rscript {0}

      # Step 4: Run R CMD check using rcmdcheck
      - name: Run R CMD check
        run: rcmdcheck::rcmdcheck(args = "--no-manual --no-build-vignettes", error_on = "error")  # Skip manual and vignettes
        shell: Rscript {0}
