# GitHub Actions Workflow for Continuous Integration with R
# This workflow runs tests on different R versions using a matrix strategy.

name: R-CI

# Trigger the workflow on push or pull request on the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Permissions for this workflow
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for faster execution
    strategy:
      matrix:
        r-version: ['3.6.3', '4.1.1']  # Test on multiple R versions

    steps:
      # Step 1: Check out the code from the repository
      - uses: actions/checkout@v4

      # Step 2: Set up the specified version of R
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      # Step 3: Install R dependencies (e.g., remotes and rcmdcheck)
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))  # Install required R packages
          remotes::install_deps(dependencies = TRUE)   # Install the package dependencies
        shell: Rscript {0}

      # Step 4: Run R CMD check to check the package
      - name: Run R CMD check
        run: rcmdcheck::rcmdcheck(args = "--no-manual --no-build-vignettes", error_on = "error")  # Skip manual and vignettes for faster checks
        shell: Rscript {0}

